# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22357375591e87f21de55e809a8b1554812e596bd5ff91c788732fa8da151f34f279e888cadf7180bbf1440bc12233eea29a98a5845a4bc30c556db33318d47a

test:
  secret_key_base: 30d859d444bde851221c750cdd1303d21a29ec89642e1aece702e53e63f475dcfc67d05243d4eaa6b6b4d5e60a8ff47ac04e98383fc99b611b13e48fc2a2b5b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
